version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: aronlebani/sharetribe
    ports:
      - "3000:3000"
    restart: always
    networks:
      - sharetribe-net
    container_name: sharetribe
    env_file: .env

  worker:
    build: .
    env_file: .env
    environment:
      - QUEUES=default,paperclip,mailers
      - MAGICK_MAP_LIMIT=64MiB
      - MAGICK_MEMORY_LIMIT=256MiB
      - MAGICK_TIME_LIMIT=30
    command: bundle exec rake jobs:work

  memcached:
    image: memcached:latest
    container_name: sharetribe_memcached

  database:
    image: mysql:5.7.27
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'sharetribe123'
      MYSQL_USER: 'sharetribe'
      MYSQL_PASSWORD: 'secret'
      MYSQL_HOST: 'sharetribe_db'
    ports:
      - '3396:3306'
    expose:
      - '3306'
    volumes:
      - ./sharetribe-db:/var/lib/mysql
    networks:
      - sharetribe-net
    container_name: sharetribe_db

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1025:1025'
      - '1080:1080'
    expose:
      - 1025
      - 1080
    container_name: sharetribe_mailcatcher

volumes:
  sharetribe-db:

networks:
  sharetribe-net:
    driver: bridge